name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN_ACCESO: ${{ secrets.DOCKER_TOKEN_ACCESO }}
      run: 
        echo "Inicio login"
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN_ACCESO
        echo "Fin login"

    #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
